version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn package
      - docker build -t no-geeks-brewing-api:latest .
      - docker tag no-geeks-brewing-api:latest public.ecr.aws/r0y0h7r0/no-geeks-brewing/no-geeks-brewing-api:latest
#  post_build:
#    commands:
#      - docker push 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api-graphql:latest