version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn package
      - docker build -t irunninglog/api-graphql:latest .