DROP TABLE IF EXISTS BATCH;
CREATE TABLE IF NOT EXISTS BATCH (id IDENTITY NOT NULL PRIMARY KEY, FOREIGN_ID VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, BATCH_NUMBER BIGINT NOT NULL, BREW_DATE BIGINT NOT NULL, STATUS VARCHAR(255) NOT NULL, STYLE VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX BATCH_FOREIGN_ID ON BATCH(FOREIGN_ID);